// Countries and capitals data for the quiz
export const countriesData = [
  // Easy level countries (commonly known)
  { country: "United States", capital: "Washington, D.C.", difficulty: "easy" },
  { country: "United Kingdom", capital: "London", difficulty: "easy" },
  { country: "France", capital: "Paris", difficulty: "easy" },
  { country: "Germany", capital: "Berlin", difficulty: "easy" },
  { country: "Italy", capital: "Rome", difficulty: "easy" },
  { country: "Spain", capital: "Madrid", difficulty: "easy" },
  { country: "Canada", capital: "Ottawa", difficulty: "easy" },
  { country: "Australia", capital: "Canberra", difficulty: "easy" },
  { country: "Japan", capital: "Tokyo", difficulty: "easy" },
  { country: "China", capital: "Beijing", difficulty: "easy" },
  { country: "Russia", capital: "Moscow", difficulty: "easy" },
  { country: "Brazil", capital: "Brasilia", difficulty: "easy" },
  { country: "India", capital: "New Delhi", difficulty: "easy" },
  { country: "Mexico", capital: "Mexico City", difficulty: "easy" },
  { country: "South Africa", capital: "Pretoria", difficulty: "easy" },
  { country: "Egypt", capital: "Cairo", difficulty: "easy" },
  { country: "Greece", capital: "Athens", difficulty: "easy" },
  { country: "Turkey", capital: "Ankara", difficulty: "easy" },
  { country: "South Korea", capital: "Seoul", difficulty: "easy" },
  { country: "Switzerland", capital: "Bern", difficulty: "easy" },
  
  // Medium level countries (mix of known and lesser-known)
  { country: "Argentina", capital: "Buenos Aires", difficulty: "medium" },
  { country: "Ireland", capital: "Dublin", difficulty: "medium" },
  { country: "Netherlands", capital: "Amsterdam", difficulty: "medium" },
  { country: "New Zealand", capital: "Wellington", difficulty: "medium" },
  { country: "Norway", capital: "Oslo", difficulty: "medium" },
  { country: "Poland", capital: "Warsaw", difficulty: "medium" },
  { country: "Portugal", capital: "Lisbon", difficulty: "medium" },
  { country: "Saudi Arabia", capital: "Riyadh", difficulty: "medium" },
  { country: "Sweden", capital: "Stockholm", difficulty: "medium" },
  { country: "Thailand", capital: "Bangkok", difficulty: "medium" },
  { country: "Ukraine", capital: "Kyiv", difficulty: "medium" },
  { country: "Vietnam", capital: "Hanoi", difficulty: "medium" },
  { country: "Austria", capital: "Vienna", difficulty: "medium" },
  { country: "Belgium", capital: "Brussels", difficulty: "medium" },
  { country: "Denmark", capital: "Copenhagen", difficulty: "medium" },
  { country: "Finland", capital: "Helsinki", difficulty: "medium" },
  { country: "Israel", capital: "Tel Aviv", difficulty: "medium" },
  { country: "Palestine", capital: "Jerusalem", difficulty: "medium" },
  { country: "Singapore", capital: "Singapore", difficulty: "medium" },
  { country: "United Arab Emirates", capital: "Abu Dhabi", difficulty: "medium" },
  { country: "Czech Republic", capital: "Prague", difficulty: "medium" },
  { country: "Hungary", capital: "Budapest", difficulty: "medium" },
  { country: "Indonesia", capital: "Jakarta", difficulty: "medium" },
  { country: "Malaysia", capital: "Kuala Lumpur", difficulty: "medium" },
  { country: "Philippines", capital: "Manila", difficulty: "medium" },
  { country: "Romania", capital: "Bucharest", difficulty: "medium" },
  { country: "Chile", capital: "Santiago", difficulty: "medium" },
  { country: "Colombia", capital: "Bogota", difficulty: "medium" },
  { country: "Peru", capital: "Lima", difficulty: "medium" },
  { country: "Venezuela", capital: "Caracas", difficulty: "medium" },
  
  // Hard level countries (lesser-known)
  { country: "Afghanistan", capital: "Kabul", difficulty: "hard" },
  { country: "Albania", capital: "Tirana", difficulty: "hard" },
  { country: "Algeria", capital: "Algiers", difficulty: "hard" },
  { country: "Andorra", capital: "Andorra la Vella", difficulty: "hard" },
  { country: "Angola", capital: "Luanda", difficulty: "hard" },
  { country: "Antigua and Barbuda", capital: "Saint John's", difficulty: "hard" },
  { country: "Armenia", capital: "Yerevan", difficulty: "hard" },
  { country: "Azerbaijan", capital: "Baku", difficulty: "hard" },
  { country: "The Bahamas", capital: "Nassau", difficulty: "hard" },
  { country: "Bahrain", capital: "Manama", difficulty: "hard" },
  { country: "Bangladesh", capital: "Dhaka", difficulty: "hard" },
  { country: "Barbados", capital: "Bridgetown", difficulty: "hard" },
  { country: "Belarus", capital: "Minsk", difficulty: "hard" },
  { country: "Belize", capital: "Belmopan", difficulty: "hard" },
  { country: "Benin", capital: "Porto-Novo", difficulty: "hard" },
  { country: "Bhutan", capital: "Thimphu", difficulty: "hard" },
  { country: "Bolivia", capital: "La Paz", difficulty: "hard" },
  { country: "Bosnia and Herzegovina", capital: "Sarajevo", difficulty: "hard" },
  { country: "Botswana", capital: "Gaborone", difficulty: "hard" },
  { country: "Brunei", capital: "Bandar Seri Begawan", difficulty: "hard" },
  { country: "Bulgaria", capital: "Sofia", difficulty: "hard" },
  { country: "Burkina Faso", capital: "Ouagadougou", difficulty: "hard" },
  { country: "Burundi", capital: "Gitega", difficulty: "hard" },
  { country: "Cambodia", capital: "Phnom Penh", difficulty: "hard" },
  { country: "Cameroon", capital: "Yaounde", difficulty: "hard" },
  { country: "Cape Verde", capital: "Praia", difficulty: "hard" },
  { country: "Central African Republic", capital: "Bangui", difficulty: "hard" },
  { country: "Chad", capital: "N'Djamena", difficulty: "hard" },
  { country: "Comoros", capital: "Moroni", difficulty: "hard" },
  { country: "Congo, Republic of the", capital: "Brazzaville", difficulty: "hard" },
  { country: "Congo, Democratic Republic of the", capital: "Kinshasa", difficulty: "hard" },
  { country: "Costa Rica", capital: "San Jose", difficulty: "hard" },
  { country: "Cote d'Ivoire", capital: "Yamoussoukro", difficulty: "hard" },
  { country: "Croatia", capital: "Zagreb", difficulty: "hard" },
  { country: "Cuba", capital: "Havana", difficulty: "hard" },
  { country: "Cyprus", capital: "Nicosia", difficulty: "hard" },
  { country: "Djibouti", capital: "Djibouti", difficulty: "hard" },
  { country: "Dominica", capital: "Roseau", difficulty: "hard" },
  { country: "Dominican Republic", capital: "Santo Domingo", difficulty: "hard" },
  { country: "East Timor", capital: "Dili", difficulty: "hard" },
  { country: "Ecuador", capital: "Quito", difficulty: "hard" },
  { country: "El Salvador", capital: "San Salvador", difficulty: "hard" },
  { country: "Equatorial Guinea", capital: "Malabo", difficulty: "hard" },
  { country: "Eritrea", capital: "Asmara", difficulty: "hard" },
  { country: "Estonia", capital: "Tallinn", difficulty: "hard" },
  { country: "Ethiopia", capital: "Addis Ababa", difficulty: "hard" },
  { country: "Fiji", capital: "Suva", difficulty: "hard" },
  { country: "Gabon", capital: "Libreville", difficulty: "hard" },
  { country: "The Gambia", capital: "Banjul", difficulty: "hard" },
  { country: "Georgia", capital: "Tbilisi", difficulty: "hard" },
  { country: "Ghana", capital: "Accra", difficulty: "hard" },
  { country: "Grenada", capital: "Saint George's", difficulty: "hard" },
  { country: "Guatemala", capital: "Guatemala City", difficulty: "hard" },
  { country: "Guinea", capital: "Conakry", difficulty: "hard" },
  { country: "Guinea-Bissau", capital: "Bissau", difficulty: "hard" },
  { country: "Guyana", capital: "Georgetown", difficulty: "hard" },
  { country: "Haiti", capital: "Port-au-Prince", difficulty: "hard" },
  { country: "Honduras", capital: "Tegucigalpa", difficulty: "hard" },
  { country: "Iceland", capital: "Reykjavik", difficulty: "hard" },
  { country: "Iran", capital: "Tehran", difficulty: "hard" },
  { country: "Iraq", capital: "Baghdad", difficulty: "hard" },
  { country: "Jamaica", capital: "Kingston", difficulty: "hard" },
  { country: "Jordan", capital: "Amman", difficulty: "hard" },
  { country: "Kazakhstan", capital: "Nur-Sultan", difficulty: "hard" },
  { country: "Kenya", capital: "Nairobi", difficulty: "hard" },
  { country: "Kiribati", capital: "Tarawa Atoll", difficulty: "hard" },
  { country: "North Korea", capital: "Pyongyang", difficulty: "hard" },
  { country: "Kosovo", capital: "Pristina", difficulty: "hard" },
  { country: "Kuwait", capital: "Kuwait City", difficulty: "hard" },
  { country: "Kyrgyzstan", capital: "Bishkek", difficulty: "hard" },
  { country: "Laos", capital: "Vientiane", difficulty: "hard" },
  { country: "Latvia", capital: "Riga", difficulty: "hard" },
  { country: "Lebanon", capital: "Beirut", difficulty: "hard" },
  { country: "Lesotho", capital: "Maseru", difficulty: "hard" },
  { country: "Liberia", capital: "Monrovia", difficulty: "hard" },
  { country: "Libya", capital: "Tripoli", difficulty: "hard" },
  { country: "Liechtenstein", capital: "Vaduz", difficulty: "hard" },
  { country: "Lithuania", capital: "Vilnius", difficulty: "hard" },
  { country: "Luxembourg", capital: "Luxembourg", difficulty: "hard" },
  { country: "Macedonia", capital: "Skopje", difficulty: "hard" },
  { country: "Madagascar", capital: "Antananarivo", difficulty: "hard" },
  { country: "Malawi", capital: "Lilongwe", difficulty: "hard" },
  { country: "Maldives", capital: "Male", difficulty: "hard" },
  { country: "Mali", capital: "Bamako", difficulty: "hard" },
  { country: "Malta", capital: "Valletta", difficulty: "hard" },
  { country: "Marshall Islands", capital: "Majuro", difficulty: "hard" },
  { country: "Mauritania", capital: "Nouakchott", difficulty: "hard" },
  { country: "Mauritius", capital: "Port Louis", difficulty: "hard" },
  { country: "Micronesia", capital: "Palikir", difficulty: "hard" },
  { country: "Moldova", capital: "Chisinau", difficulty: "hard" },
  { country: "Monaco", capital: "Monaco", difficulty: "hard" },
  { country: "Mongolia", capital: "Ulaanbaatar", difficulty: "hard" },
  { country: "Montenegro", capital: "Podgorica", difficulty: "hard" },
  { country: "Morocco", capital: "Rabat", difficulty: "hard" },
  { country: "Mozambique", capital: "Maputo", difficulty: "hard" },
  { country: "Myanmar", capital: "Naypyidaw", difficulty: "hard" },
  { country: "Namibia", capital: "Windhoek", difficulty: "hard" },
  { country: "Nauru", capital: "Yaren District", difficulty: "hard" },
  { country: "Nepal", capital: "Kathmandu", difficulty: "hard" },
  { country: "Nicaragua", capital: "Managua", difficulty: "hard" },
  { country: "Niger", capital: "Niamey", difficulty: "hard" },
  { country: "Nigeria", capital: "Abuja", difficulty: "hard" },
  { country: "Oman", capital: "Muscat", difficulty: "hard" },
  { country: "Pakistan", capital: "Islamabad", difficulty: "hard" },
  { country: "Palau", capital: "Melekeok", difficulty: "hard" },
  { country: "Panama", capital: "Panama City", difficulty: "hard" },
  { country: "Papua New Guinea", capital: "Port Moresby", difficulty: "hard" },
  { country: "Paraguay", capital: "Asuncion", difficulty: "hard" },
  { country: "Qatar", capital: "Doha", difficulty: "hard" },
  { country: "Rwanda", capital: "Kigali", difficulty: "hard" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre", difficulty: "hard" },
  { country: "Saint Lucia", capital: "Castries", difficulty: "hard" },
  { country: "Saint Vincent and the Grenadines", capital: "Kingstown", difficulty: "hard" },
  { country: "Samoa", capital: "Apia", difficulty: "hard" },
  { country: "San Marino", capital: "San Marino", difficulty: "hard" },
  { country: "Sao Tome and Principe", capital: "Sao Tome", difficulty: "hard" },
  { country: "Senegal", capital: "Dakar", difficulty: "hard" },
  { country: "Serbia", capital: "Belgrade", difficulty: "hard" },
  { country: "Seychelles", capital: "Victoria", difficulty: "hard" },
  { country: "Sierra Leone", capital: "Freetown", difficulty: "hard" },
  { country: "Slovakia", capital: "Bratislava", difficulty: "hard" },
  { country: "Slovenia", capital: "Ljubljana", difficulty: "hard" },
  { country: "Solomon Islands", capital: "Honiara", difficulty: "hard" },
  { country: "Somalia", capital: "Mogadishu", difficulty: "hard" },
  { country: "South Sudan", capital: "Juba", difficulty: "hard" },
  { country: "Sri Lanka", capital: "Colombo", difficulty: "hard" },
  { country: "Sudan", capital: "Khartoum", difficulty: "hard" },
  { country: "Suriname", capital: "Paramaribo", difficulty: "hard" },
  { country: "Swaziland", capital: "Mbabane", difficulty: "hard" },
  { country: "Syria", capital: "Damascus", difficulty: "hard" },
  { country: "Taiwan", capital: "Taipei", difficulty: "hard" },
  { country: "Tajikistan", capital: "Dushanbe", difficulty: "hard" },
  { country: "Tanzania", capital: "Dodoma", difficulty: "hard" },
  { country: "Togo", capital: "Lome", difficulty: "hard" },
  { country: "Tonga", capital: "Nuku'alofa", difficulty: "hard" },
  { country: "Trinidad and Tobago", capital: "Port-of-Spain", difficulty: "hard" },
  { country: "Tunisia", capital: "Tunis", difficulty: "hard" },
  { country: "Turkmenistan", capital: "Ashgabat", difficulty: "hard" },
  { country: "Tuvalu", capital: "Funafuti", difficulty: "hard" },
  { country: "Uganda", capital: "Kampala", difficulty: "hard" },
  { country: "Uruguay", capital: "Montevideo", difficulty: "hard" },
  { country: "Uzbekistan", capital: "Tashkent", difficulty: "hard" },
  { country: "Vanuatu", capital: "Port-Vila", difficulty: "hard" },
  { country: "Vatican City", capital: "Vatican City", difficulty: "hard" },
  { country: "Yemen", capital: "Sanaa", difficulty: "hard" },
  { country: "Zambia", capital: "Lusaka", difficulty: "hard" },
  { country: "Zimbabwe", capital: "Harare", difficulty: "hard" },
];

// Function to get random countries based on difficulty
export function getQuizQuestions(difficulty, count = 10) {
  const filteredCountries = difficulty === 'all' 
    ? countriesData 
    : countriesData.filter(item => item.difficulty === difficulty);
  
  // Shuffle the array
  const shuffled = [...filteredCountries].sort(() => 0.5 - Math.random());
  
  // Take the first 'count' items or all if there are fewer
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

// Function to generate multiple choice options for a question
export function generateOptions(correctCapital) {
  // Get the correct answer
  const correctAnswer = correctCapital;
  
  // Get 3 random wrong answers
  const otherCapitals = countriesData
    .map(item => item.capital)
    .filter(capital => capital !== correctAnswer)
    .sort(() => 0.5 - Math.random())
    .slice(0, 3);
  
  // Combine correct and wrong answers, then shuffle
  const options = [correctAnswer, ...otherCapitals].sort(() => 0.5 - Math.random());
  
  return options;
}

// Quiz settings based on difficulty
export const quizSettings = {
  easy: {
    timePerQuestion: 20, // seconds
    pointsPerQuestion: 10,
    speedBonus: 0.5, // multiplier for time left
  },
  medium: {
    timePerQuestion: 15,
    pointsPerQuestion: 15,
    speedBonus: 0.75,
  },
  hard: {
    timePerQuestion: 8, // Changed from 10 to 8 seconds
    pointsPerQuestion: 20,
    speedBonus: 1,
  },
}; 